library(rvest)
html <- read_html("https://www.imdb.com/search/title?groups=top_250&sort=user_rating")
nods <- html_nodes(html, ".lister-item-header")
Movies <- html_text(nods)
df <- data.frame(Movies)
View(df)
